
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "web_scraper_cli"
version = "1.0.0"
edition = "2021"
description = "A CLI tool to scrape webpages and export content"
license = "MIT"
authors = ["softxtbx <softonchain@gmail.com>"]

[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
scraper = "0.18"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
csv = "1.3"
clap = { version = "4.5", features = ["derive"] }
futures = "0.3"
chrono = "0.4"
serenity = { version = "0.11", default-features = false, features = ["client", "gateway", "http", "model", "rustls_backend"] }
dotenv = "0.15"
[[bin]]
name = "bot_main"
path = "src/bot_main.rs"